version: '3.8'

services:
  travelquest-mysql:
    image: mysql:latest
    container_name: travelquest-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ssafytrip
      MYSQL_USER: travelquest
      MYSQL_PASSWORD: travelquest
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_0900_ai_ci
    volumes:
    - ./mysql/initdb:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - travelquest-network

  travelquest-adminer:
    image: adminer:latest
    container_name: travelquest-adminer
    environment:
      ADMINER_DEFAULT_SERVER: travelquest-mysql
    ports:
      - "18080:8080"
    networks:
      - travelquest-network

  travelquest-redis:
    image: redis:latest
    container_name: travelquest-redis
    ports:
      - "6379:6379"
    networks:
      - travelquest-network

  travelquest-mongodb:
    image: mongo:latest
    container_name: travelquest-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    restart: unless-stopped
    networks:
      - travelquest-network

  travelquest-mongo-express:
    image: mongo-express:latest
    container_name: travelquest-mongo-express
    ports:
      - "18081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:root@travelquest-mongodb:27017/?authSource=admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - travelquest-mongodb
    networks:
      - travelquest-network

networks:
  travelquest-network:
    driver: bridge

volumes:
  mongo_data:
