version: '3.8'

services:
  travelquest-mysql:
    image: mysql:latest
    container_name: travelquest-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ssafytrip
      MYSQL_USER: travelquest
      MYSQL_PASSWORD: travelquest
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_0900_ai_ci
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - travelquest-network

  travelquest-adminer:
    image: adminer:latest
    container_name: travelquest-adminer
    environment:
      ADMINER_DEFAULT_SERVER: travelquest-mysql
    ports:
      - "18080:8080"
    networks:
      - travelquest-network

  travelquest-redis:
    image: redis:latest
    container_name: travelquest-redis
    ports:
      - "6379:6379"
    networks:
      - travelquest-network

networks:
  travelquest-network:
    driver: bridge
